### ISSUE TITLE
Deprecation warnings with Webpack 4

### ISSUE THREAD

**Issue by scitech** [aduth/resolve-entry-modules-webpack-plugin#3]
Hello, I'm encountering a few deprecation warnings when using this plugin, related to the plugin itself and also the version of `enhanced-resolve` being used:

```
(node:20716) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead                                                                                    
    at ResolveEntryModulesPlugin.apply (node_modules/resolve-entry-modules-webpack-plugin/index.js:70:12)
...
(node:20716) DeprecationWarning: webpack: Using compiler.resolvers.normal is deprecated.
Use compiler.resolverFactory.plugin("resolver normal", resolver => {
  resolver.apply(/* … */);
}); instead.
    at compiler.plugin (node_modules/resolve-entry-modules-webpack-plugin/index.js:71:30)
...
(node:20716) DeprecationWarning: The callback argument was splitted into resolveContext and callback.
    at Resolver.doResolve (node_modules/enhanced-resolve/lib/Resolver.js:189:15)
    at Resolver.resolver.plugin (node_modules/resolve-entry-modules-webpack-plugin/index.js:90:16)
...
(node:20716) DeprecationWarning: The type arguments (string) is now a hook argument (Hook). Pass a reference to the hook instead.
    at Resolver.doResolve (node_modules/enhanced-resolve/lib/Resolver.js:193:11)
    at Resolver.resolver.plugin (node_modules/resolve-entry-modules-webpack-plugin/index.js:90:16)

```

It works fine, since the deprecations won't take full effect until the next major webpack release. See also:
https://github.com/webpack/webpack/issues/6568#issuecomment-377491754

Do you have any plans to use the newer API, or would you accept a PR? Thanks.

**Comment by aduth** [comment]
Thanks for raising this issue. I have no opposition to updating to use the new API. I'd happily accept a pull request, or I can add it to my own agenda, though it will not be a priority item for me in the near immediate future.

**Comment by scitech** [comment]
Fixed in https://github.com/aduth/resolve-entry-modules-webpack-plugin/pull/4
